### week 1 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/
POST http://localhost:8080/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Northern Illinois",
        "awayTeamName": "Utah",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 36,
        "awayScore": 31
    },
    {
        "homeTeamName": "Syracuse",
        "awayTeamName": "Ohio",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 49,
        "awayScore": 0
    },{
        "homeTeamName": "Buffalo",
        "awayTeamName": "Iowa",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 7,
        "awayScore": 45
    },{
        "homeTeamName": "UMass",
        "awayTeamName": "Eastern Michigan",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 45,
        "awayScore": 17
    },{
        "homeTeamName": "Oregon",
        "awayTeamName": "Ball State",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 56,
        "awayScore": 3
    },
    {
        "homeTeamName": "Kent State",
        "awayTeamName": "Toledo",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 42,
        "awayScore": 21
    },
    {
        "homeTeamName": "Miami-OH",
        "awayTeamName": "Akron",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 35,
        "awayScore": 0
    },
    {
        "homeTeamName": "Bowling Green",
        "awayTeamName": "Tennessee",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 7,
        "awayScore": 35
    },
    {
        "homeTeamName": "Central Michigan",
        "awayTeamName": "Oklahoma State",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 16,
        "awayScore": 28
    },
    {
        "homeTeamName": "Jacksonville State",
        "awayTeamName": "Western Michigan",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 1,
        "homeScore": 14,
        "awayScore": 31
    }
]

### week 2 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/
POST http://localhost:8080/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Penn State",
        "awayTeamName": "Bowling Green",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 37,
        "awayScore": 30
    },
    {
        "homeTeamName": "Missouri",
        "awayTeamName": "Buffalo",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 34,
        "awayScore": 7
    },{
        "homeTeamName": "Northwestern",
        "awayTeamName": "Miami-OH",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 28,
        "awayScore": 7
    },{
        "homeTeamName": "Wisconsin",
        "awayTeamName": "Western Michigan",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 49,
        "awayScore": 7
    },{
        "homeTeamName": "Pittsburgh",
        "awayTeamName": "Kent State",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 39,
        "awayScore": 14
    },
    {
        "homeTeamName": "Ohio State",
        "awayTeamName": "Akron",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 48,
        "awayScore": 20
    },
    {
        "homeTeamName": "Ohio",
        "awayTeamName": "South Alabama",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 31,
        "awayScore": 20
    },
    {
        "homeTeamName": "Florida International",
        "awayTeamName": "Central Michigan",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 24,
        "awayScore": 14
    },
    {
        "homeTeamName": "Toledo",
        "awayTeamName": "UMass",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 30,
        "awayScore": 3
    },
    {
        "homeTeamName": "Notre Dame",
        "awayTeamName": "Northern Illinois",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 24,
        "awayScore": 17
    },
    {
        "homeTeamName": "Jacksonville State",
        "awayTeamName": "Ball State",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 7,
        "awayScore": 30
    },
    {
        "homeTeamName": "Washington",
        "awayTeamName": "Eastern Michigan",
        "date": "2024-07-25",
        "year": 2024,
        "weekNumber": 2,
        "homeScore": 21,
        "awayScore": 28
    }
]

### week 3 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/
POST http://localhost:8080/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Jacksonville State",
        "awayTeamName": "Eastern Michigan",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 16,
        "awayScore": 21
    },
    {
        "homeTeamName": "Rutgers",
        "awayTeamName": "Akron",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 38,
        "awayScore": 24
    },{
        "homeTeamName": "Illinois",
        "awayTeamName": "Central Michigan",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 38,
        "awayScore": 7
    },{
        "homeTeamName": "Miami",
        "awayTeamName": "Ball State",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 14,
        "awayScore": 21
    },{
        "homeTeamName": "Buffalo",
        "awayTeamName": "UMass",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 20,
        "awayScore": 10
    },
    {
        "homeTeamName": "Ohio State",
        "awayTeamName": "Western Michigan",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 38,
        "awayScore": 7
    },
    {
        "homeTeamName": "Tennessee",
        "awayTeamName": "Kent State",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 27,
        "awayScore": 14
    },
    {
        "homeTeamName": "Cincinnati",
        "awayTeamName": "Miami-OH",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 41,
        "awayScore": 17
    },
    {
        "homeTeamName": "Mississippi State",
        "awayTeamName": "Toledo",
        "date": "2024-07-29",
        "year": 2024,
        "weekNumber": 3,
        "homeScore": 24,
        "awayScore": 28
    }
]

### week 4 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/
POST http://localhost:8080/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Western Kentucky",
        "awayTeamName": "Toledo",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 35,
        "awayScore": 42
    },
    {
        "homeTeamName": "South Carolina",
        "awayTeamName": "Akron",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 35,
        "awayScore": 14
    },{
        "homeTeamName": "Penn State",
        "awayTeamName": "Kent State",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 44,
        "awayScore": 3
    },{
        "homeTeamName": "Eastern Michigan",
        "awayTeamName": "FCS West",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 45,
        "awayScore": 41
    },{
        "homeTeamName": "Ball State",
        "awayTeamName": "Central Michigan",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 22,
        "awayScore": 31
    },
    {
        "homeTeamName": "Kentucky",
        "awayTeamName": "Ohio",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 7,
        "awayScore": 10
    },
    {
        "homeTeamName": "Notre Dame",
        "awayTeamName": "Miami-OH",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 35,
        "awayScore": 28
    },
    {
        "homeTeamName": "Jacksonville State",
        "awayTeamName": "Bowling Green",
        "date": "2024-08-01",
        "year": 2024,
        "weekNumber": 4,
        "homeScore": 22,
        "awayScore": 41
    }
]

### week 5 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/
POST http://localhost:8080/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Jacksonville State",
        "awayTeamName": "Toledo",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 14,
        "awayScore": 27
    },
    {
        "homeTeamName": "UConn",
        "awayTeamName": "Buffalo",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 17,
        "awayScore": 38
    },{
        "homeTeamName": "Miami-OH",
        "awayTeamName": "UMass",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 14,
        "awayScore": 35
    },{
        "homeTeamName": "Bowling Green",
        "awayTeamName": "Old Dominion",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 34,
        "awayScore": 11
    },{
        "homeTeamName": "NC State",
        "awayTeamName": "Northern Illinois",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 7,
        "awayScore": 35
    },
    {
        "homeTeamName": "Akron",
        "awayTeamName": "UTEP",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 9,
        "awayScore": 52
    },
    {
        "homeTeamName": "Eastern Michigan",
        "awayTeamName": "Kent State",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 51,
        "awayScore": 3
    },
    {
        "homeTeamName": "Central Michigan",
        "awayTeamName": "San Diego State",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 30,
        "awayScore": 42
    },
    {
        "homeTeamName": "James Madison",
        "awayTeamName": "Ball State",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 17,
        "awayScore": 21
    },
    {
        "homeTeamName": "Marshall",
        "awayTeamName": "Western Michigan",
        "date": "2024-08-04",
        "year": 2024,
        "weekNumber": 5,
        "homeScore": 35,
        "awayScore": 21
    }
]

### week 6 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/
POST https://quiet-waters-73507-4fc26eff764d.herokuapp.com/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Ohio",
        "awayTeamName": "Jacksonville State",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 6,
        "homeScore": 20,
        "awayScore": 14
    },
    {
        "homeTeamName": "Western Michigan",
        "awayTeamName": "Toledo",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 6,
        "homeScore": 14,
        "awayScore": 28
    },
    {
        "homeTeamName": "Buffalo",
        "awayTeamName": "Miami-OH",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 6,
        "homeScore": 31,
        "awayScore": 0
    },
    {
        "homeTeamName": "Northern Illinois",
        "awayTeamName": "UMass",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 6,
        "homeScore": 35,
        "awayScore": 41
    },
    {
        "homeTeamName": "Akron",
        "awayTeamName": "Bowling Green",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 6,
        "homeScore": 3,
        "awayScore": 28
    }
]

### week 7 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/ http://localhost:8080
POST https://quiet-waters-73507-4fc26eff764d.herokuapp.com/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Central Michigan",
        "awayTeamName": "Jacksonville State",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 24,
        "awayScore": 17
    },
    {
        "homeTeamName": "Ohio",
        "awayTeamName": "Indiana",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 29,
        "awayScore": 28
    },{
        "homeTeamName": "Bowling Green",
        "awayTeamName": "Northern Illinois",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 7,
        "awayScore": 33
    },{
        "homeTeamName": "Toledo",
        "awayTeamName": "Buffalo",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 27,
        "awayScore": 7
    },{
        "homeTeamName": "Eastern Michigan",
        "awayTeamName": "Miami-OH",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 35,
        "awayScore": 42
    },
    {
        "homeTeamName": "Ball State",
        "awayTeamName": "Akron",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 20,
        "awayScore": 16
    },
    {
        "homeTeamName": "Western Michigan",
        "awayTeamName": "Duke",
        "date": "2024-08-11",
        "year": 2024,
        "weekNumber": 7,
        "homeScore": 31,
        "awayScore": 28
    }
]

### week 8 https://quiet-waters-73507-4fc26eff764d.herokuapp.com/ http://localhost:8080
POST https://quiet-waters-73507-4fc26eff764d.herokuapp.com/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Miami-OH",
        "awayTeamName": "Ohio",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 33,
        "awayScore": 28
    },
    {
        "homeTeamName": "Eastern Michigan",
        "awayTeamName": "Central Michigan",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 7,
        "awayScore": 59
    },
    {
        "homeTeamName": "Buffalo",
        "awayTeamName": "Western Michigan",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 14,
        "awayScore": 38
    },
    {
        "homeTeamName": "Vanderbilt",
        "awayTeamName": "Ball State",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 39,
        "awayScore": 36
    },
    {
        "homeTeamName": "Jacksonville State",
        "awayTeamName": "Akron",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 0,
        "awayScore": 0
    },
    {
        "homeTeamName": "Bowling Green",
        "awayTeamName": "Kent State",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 0,
        "awayScore": 0
    },
    {
        "homeTeamName": "Northern Illinois",
        "awayTeamName": "Toledo",
        "date": "2024-08-14",
        "year": 2024,
        "weekNumber": 8,
        "homeScore": 26,
        "awayScore": 43
    }
]

### 
POST https://quiet-waters-73507-4fc26eff764d.herokuapp.com/api/v1.0/createGames HTTP/1.1
content-type: application/json

[
    {
        "homeTeamName": "Akron",
        "awayTeamName": "Bowling Green",
        "date": "2024-07-21",
        "year": 2024,
        "weekNumber": 6,
        "homeScore": 3,
        "awayScore": 28
    }
]